// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_PC2wglOYgQ7wbVjETY61jtCrZEYoyY4',
    appId: '1:675661755718:web:abf660f934027e82ada147',
    messagingSenderId: '675661755718',
    projectId: 'andrianiiainaquote',
    authDomain: 'andrianiiainaquote.firebaseapp.com',
    storageBucket: 'andrianiiainaquote.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVucgpjHFBJYSCd8SgzNLLl9FJSoPJN8w',
    appId: '1:675661755718:android:c874070e1649be57ada147',
    messagingSenderId: '675661755718',
    projectId: 'andrianiiainaquote',
    storageBucket: 'andrianiiainaquote.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy5jhQ00NDUUlav64V_etuB-j07JvpQ8k',
    appId: '1:675661755718:ios:e4882b84b88647e0ada147',
    messagingSenderId: '675661755718',
    projectId: 'andrianiiainaquote',
    storageBucket: 'andrianiiainaquote.appspot.com',
    iosBundleId: 'com.example.andrianiaiinaQuote',
  );
}
